SET DEFINE OFF;
Insert into FB_LIGNE_TIERS_PIECE
   (IDE_POSTE, IDE_GEST, IDE_ORDO, COD_BUD, IDE_PIECE, 
    NUM_LIG, COD_TYP_PIECE, VAR_CPTA, IDE_CPT, VAR_TIERS, 
    IDE_TIERS, COD_CAT_SOCIOP, COD_TYP_TIERS, COD_SEC, NOM, 
    PRENOM, COD_RETENUE, FLG_OPPO, COD_MODE_REGLEMT, MT, 
    MTT_RETENUE_OPPO, COD_SENS, ADR1, ADR2, ADR3, 
    ADR4, VILLE, CP, BP, PAYS, 
    CPT_BQ, NOM_BQ, NOM_CONTRIB, TELEPH, DAT_CRE, 
    UTI_CRE, DAT_MAJ, UTI_MAJ, TERMINAL, NUM_BQ, 
    IDE_REF_PIECE, MT_DEV, SPEC1, IDE_PLAN_AUX, IDE_CPT_AUX, 
    LIB_OBJET_REGLT, IDE_DEVISE, VAL_TAUX)
 Values
   ('418C', '2020', 'CPT830001', 'BGDEP', '210059020800670', 
    1, 'OD', 'C2020', '47412', 'T2012', 
    '1234418C', NULL, 'M', NULL, 'BOXBROADBAND', 
    'BOXBROADBAND', NULL, NULL, 'VRB', 58783, 
    0, 'C', '39 HIGH STREET - CRANLEIGH - SUR', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    '80395064', 'BARCLAYS BANK', 'BOXBROADBAND', 'NULL', TO_DATE('07/01/2021 10:16:54', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', TO_DATE('07/01/2021 10:16:54', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', 'pts/0', 81, 
    NULL, 79.95, NULL, NULL, NULL, 
    NULL, NULL, NULL);
COMMIT;
