SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    1, 'C2020', NULL, NULL, '390307212', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 3500000, '39111', '47012106', 
    '506', NULL, NULL, NULL, '4', 
    'A', '307212', TO_DATE('20/08/2024', 'DD/MM/YYYY'), TO_DATE('26/08/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('26/08/2024 12:44:53', 'DD/MM/YYYY HH24:MI:SS'), '276708U', TO_DATE('26/08/2024 12:44:53', 'DD/MM/YYYY HH24:MI:SS'), 
    '276708U', '10.10.200.154', 'N', NULL, NULL, 
    NULL, NULL, 3500000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    2, 'C2020', NULL, NULL, '4751411', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 3500000, NULL, NULL, 
    NULL, NULL, NULL, NULL, '4', 
    'A', 'C 4751411', TO_DATE('20/08/2024', 'DD/MM/YYYY'), TO_DATE('26/08/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('26/08/2024 12:44:53', 'DD/MM/YYYY HH24:MI:SS'), '276708U', TO_DATE('26/08/2024 12:44:53', 'DD/MM/YYYY HH24:MI:SS'), 
    '276708U', '10.10.200.154', 'N', NULL, NULL, 
    NULL, NULL, 3500000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    3, 'C2020', NULL, NULL, '4751411', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 13560825, NULL, NULL, 
    NULL, NULL, NULL, NULL, '4', 
    'A', 'D 4751411', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 'ASDEV', TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASDEV', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, 13560825, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    4, 'C2020', NULL, NULL, '39030202', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 72775, '39112', '4663154', 
    '502', NULL, NULL, NULL, '4', 
    'A', '30202', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 'ASDEV', TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASDEV', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, 72775, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    5, 'C2020', NULL, NULL, '515111312', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 13701325, NULL, NULL, 
    NULL, NULL, NULL, NULL, '4', 
    'A', 'C 515111312', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 'ASDEV', TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASDEV', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, 13701325, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('2093', '2024', 'T10BISACP', 'O', 23, 
    6, 'C2020', NULL, '507', '47012402', 
    NULL, 'T20D NO 11/2024 FRAIS BANC APTF PC2093 10/08/2024', NULL, NULL, NULL, 
    NULL, 'D', 10500, NULL, NULL, 
    NULL, NULL, NULL, NULL, '4', 
    'A', 'D 47012402', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 'ASDEV', TO_DATE('22/08/2024 12:29:43', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASDEV', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, 10500, NULL, NULL, 
    NULL);
COMMIT;
