SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1415, 
    2, 'C2020', NULL, NULL, '4433', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 131975, NULL, NULL, 
    NULL, 'ACHAT FOURNITURES TECHNIQUES POUR LE CONTROLE', NULL, NULL, '2', 
    'T', 'D 4433', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 131975, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1413, 
    1, 'C2020', NULL, NULL, '39030202', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 22355, '39112', '4663154', 
    '502', 'ACHAT DE FOURNITURES DE BUREAU POUR LE CONTRO', NULL, NULL, '2', 
    'T', 'CREDIT+3SPEC', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 22355, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1415, 
    1, 'C2020', NULL, NULL, '39030202', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 131975, '39112', '4663154', 
    '502', 'ACHAT FOURNITURES TECHNIQUES POUR LE CONTROLE', NULL, NULL, '2', 
    'T', 'CREDIT+3SPEC', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 131975, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1413, 
    2, 'C2020', NULL, NULL, '4433', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 22355, NULL, NULL, 
    NULL, 'ACHAT DE FOURNITURES DE BUREAU POUR LE CONTRO', NULL, NULL, '2', 
    'T', 'D 4433', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 22355, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1418, 
    2, 'C2020', NULL, NULL, '4433', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 18626, NULL, NULL, 
    NULL, 'ACHAT DE FOURNITURES D4HYGIENE POUR LE COMTRO', NULL, NULL, '2', 
    'T', 'D 4433', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 18626, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3086', '2023', 'T29EPN', 'N', 1418, 
    1, 'C2020', NULL, NULL, '39030202', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 18626, '39112', '4663154', 
    '502', 'ACHAT DE FOURNITURES D4HYGIENE POUR LE COMTRO', NULL, NULL, '2', 
    'T', 'CREDIT+3SPEC', NULL, TO_DATE('06/02/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('07/02/2023 08:58:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 18626, NULL, NULL, 
    NULL);
COMMIT;
