SET DEFINE OFF;
Insert into T_COMPTE_MER
   (EAD_GST_ANNEE, EAD_CDE_PC_ASSI, IDE_SCHEMA, IDE_MODEL_LIGNE, CPT_CREDIT, 
    CPT_DEBIT, IDE_JAL, IDE_MODEL_LIGNE_CREDIT, NUM_LIG, DESTINATION, 
    FLG_CUT)
 Values
   (2021, '508', '1', 'DEBIT', '4701121', 
    '401122', 'JODPGA', 'CREDIT+T', 1, NULL, 
    'O');
COMMIT;
