SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('410', '2025', 'A29', 'O', 888, 
    TO_DATE('30/06/2025', 'DD/MM/YYYY'), 'C2020', '6', 'P', '410', 
    NULL, 'R', 'Ecart de change', TO_DATE('15/07/2025 08:51:00', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('30/06/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('15/07/2025 08:51:00', 'DD/MM/YYYY HH24:MI:SS'), 'SYS', TO_DATE('15/07/2025 08:51:00', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYS', 'SYS', NULL, NULL, NULL, 
    NULL);
COMMIT;
