SET DEFINE OFF;
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('423C', '2024', 'JTRANSFERT', 'O', 16, 
    2, 'C2020', NULL, NULL, '39112', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 39297526, NULL, NULL, 
    NULL, 'CHQ.7088032.TRESOR.PUBL.ACCT_REL 5/4/24', NULL, NULL, 'RECETTES', 
    'A', 'DEBIT', TO_DATE('17/04/2024', 'DD/MM/YYYY'), TO_DATE('15/04/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('05/09/2024 11:33:50', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('05/09/2024 11:33:50', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    'XOF', 1, 39297526, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('423C', '2024', 'JTRANSFERT', 'O', 16, 
    1, 'C2020', NULL, NULL, '39032', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 39297526, NULL, NULL, 
    NULL, 'CHQ.7088032.TRESOR.PUBL.ACCT_REL 5/4/24', NULL, NULL, 'RECETTES', 
    'A', 'CREDIT', TO_DATE('17/04/2024', 'DD/MM/YYYY'), TO_DATE('15/04/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('05/09/2024 11:33:50', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('05/09/2024 11:33:50', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    'XOF', 1, 39297526, NULL, NULL, 
    NULL);
COMMIT;
