SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 17, 
    NULL, 'C2020', 'DEPENSES', 'P', '430C', 
    2624, 'R', 'Transfert 430C du 16/07/25', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 11, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 18, 
    NULL, 'C2020', 'DEPENSES', 'P', '430C', 
    2624, 'R', 'Transfert 430C du 16/07/25', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 11, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 19, 
    NULL, 'C2020', 'DEPENSES', 'P', '430C', 
    2624, 'R', 'Transfert 430C du 16/07/25', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 11, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('29/07/2025 20:35:29', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 16, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    32399, 'R', 'Transfert 517 du 25/07/25', TO_DATE('28/07/2025 12:33:49', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 16, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('28/07/2025 12:33:49', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('28/07/2025 12:33:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 20, 
    NULL, 'C2020', 'DEPENSES', 'P', '517', 
    32405, 'R', 'Transfert 517 du 05/08/25', TO_DATE('05/08/2025 12:32:31', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 17, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('05/08/2025 12:32:31', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('05/08/2025 12:32:31', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 15, 
    NULL, 'C2020', 'RECETTES', 'P', '414C', 
    3189, 'R', 'Transfert 414C du 17/07/25', TO_DATE('17/07/2025 16:19:05', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 45, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('17/07/2025 16:19:05', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('17/07/2025 16:19:05', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 14, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    32381, 'R', 'Transfert 517 du 04/07/25', TO_DATE('09/07/2025 10:14:21', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 14, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/07/2025 10:14:21', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('09/07/2025 10:14:21', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 13, 
    NULL, 'C2020', 'DEPENSES', 'P', '414C', 
    3172, 'R', 'Transfert 414C du 30/06/25', TO_DATE('03/07/2025 08:15:42', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 42, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('03/07/2025 08:15:42', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('03/07/2025 08:15:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 4, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    31599, 'R', 'Transfert 517 du 27/05/25', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 10, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 5, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    31599, 'R', 'Transfert 517 du 27/05/25', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 10, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 6, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    31599, 'R', 'Transfert 517 du 27/05/25', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 10, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 7, 
    NULL, 'C2020', 'RECETTES', 'P', '517', 
    31599, 'R', 'Transfert 517 du 27/05/25', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 10, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('28/05/2025 15:34:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 8, 
    NULL, 'C2020', 'RECETTES', 'P', '663C', 
    14398, 'R', 'Transfert 663C du 30/05/25', TO_DATE('10/06/2025 11:09:48', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 34, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('10/06/2025 11:09:48', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('10/06/2025 11:09:48', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 3, 
    NULL, 'C2020', 'RECETTES', 'P', '414C', 
    3134, 'R', 'Transfert 414C du 19/05/25', TO_DATE('19/05/2025 18:04:14', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 29, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('19/05/2025 18:04:14', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('19/05/2025 18:04:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 1, 
    NULL, 'C2020', 'RECETTES', 'P', '502', 
    123453, 'R', 'Transfert 502 du 09/05/25', TO_DATE('15/05/2025 16:05:52', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 96, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('15/05/2025 16:05:52', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('15/05/2025 16:05:52', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 2, 
    NULL, 'C2020', 'RECETTES', 'P', '663C', 
    14381, 'R', 'Transfert 663C du 09/05/25', TO_DATE('19/05/2025 07:57:05', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 29, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('19/05/2025 07:57:06', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('19/05/2025 07:57:06', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 9, 
    NULL, 'C2020', 'DEPENSES', 'P', '414C', 
    3157, 'R', 'Transfert 414C du 11/06/25', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 38, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 10, 
    NULL, 'C2020', 'DEPENSES', 'P', '414C', 
    3157, 'R', 'Transfert 414C du 11/06/25', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 38, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 11, 
    NULL, 'C2020', 'RECETTES', 'P', '414C', 
    3157, 'R', 'Transfert 414C du 11/06/25', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 38, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ, IDE_GEST_REF, 
    IDE_PIECE_REF)
 Values
   ('501C', '2025', 'JTRANSFERT', 'N', 12, 
    NULL, 'C2020', 'RECETTES', 'P', '414C', 
    3157, 'R', 'Transfert 414C du 11/06/25', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    'AC', 38, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2025 13:07:17', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'MES', NULL, NULL, NULL, 
    NULL);
COMMIT;
