SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('514', '2024', 'T10BIS', 'N', 83081, 
    1, 'C2020', NULL, NULL, '571', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 40466375, NULL, NULL, 
    NULL, 'Travaux damenagement de la cour en bitume sur', NULL, NULL, '5', 
    'T', 'C 571', NULL, TO_DATE('11/04/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('17/04/2024 12:54:05', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('17/04/2024 12:54:05', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 40466375, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('514', '2024', 'T10BIS', 'N', 83081, 
    2, 'C2020', NULL, NULL, '40221', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 40466375, NULL, NULL, 
    NULL, 'Travaux damenagement de la cour en bitume sur', NULL, NULL, '5', 
    'T', 'DEBIT', NULL, TO_DATE('11/04/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('17/04/2024 12:54:05', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('17/04/2024 12:54:05', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 40466375, NULL, NULL, 
    NULL);
COMMIT;
