SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('614C', '2024', 'JPECDEPBG', 'O', 1, 
    1, 'C2020', NULL, NULL, '4081', 
    NULL, NULL, 'BGD20', '35035047300003618300', NULL, 
    'T400016', 'D', 124800, NULL, NULL, 
    NULL, 'Consommation internet', NULL, NULL, '1', 
    'A', 'PEC90', TO_DATE('21/05/2024', 'DD/MM/YYYY'), NULL, 'D', 
    'BGDEP', NULL, TO_DATE('27/05/2024 15:14:38', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', TO_DATE('27/05/2024 15:14:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, 124800, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('614C', '2024', 'JPECDEPBG', 'O', 1, 
    180, 'C2020', NULL, NULL, '47411', 
    NULL, NULL, 'BGD20', NULL, NULL, 
    'T400016', 'C', 124800, NULL, NULL, 
    NULL, 'Consommation internet', NULL, NULL, '1', 
    'A', 'PEC40', TO_DATE('21/05/2024', 'DD/MM/YYYY'), NULL, NULL, 
    NULL, NULL, TO_DATE('27/05/2024 15:14:38', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', TO_DATE('27/05/2024 15:14:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, 124800, NULL, NULL, 
    NULL);
COMMIT;
