SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('620', '2021', 'T29', 'N', 7682718, 
    1, 'C2020', NULL, NULL, '47512223', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 216260, NULL, NULL, 
    NULL, 'REJET Depenses de representation et de recept', NULL, NULL, '8', 
    'T', 'CREDIT', NULL, TO_DATE('02/12/2021', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('08/02/2023 12:27:37', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('08/02/2023 12:27:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 216260, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('620', '2021', 'T29', 'N', 7682718, 
    2, 'C2020', NULL, NULL, '572', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 216260, NULL, NULL, 
    NULL, 'REJET Depenses de representation et de recept', NULL, NULL, '8', 
    'T', 'D 572', NULL, TO_DATE('02/12/2021', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('08/02/2023 12:27:37', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('08/02/2023 12:27:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 216260, NULL, NULL, 
    NULL);
COMMIT;
