SET DEFINE OFF;
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('627', '2022', 'T21D', 'O', 2382, 
    2, 'C2020', NULL, NULL, '390303011', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 14146, '39111', '431112', 
    '501', 'PENSION IVOIRIENNE FEVRIER 2022-', TO_DATE('06/12/2022 17:01:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, '3', 
    'T', 'DEBIT+3SPEC', TO_DATE('06/12/2022', 'DD/MM/YYYY'), TO_DATE('21/04/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('03/01/2023 10:45:51', 'DD/MM/YYYY HH24:MI:SS'), 'NIABA', TO_DATE('03/01/2023 10:45:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'NIABA', 'ACCT242', 'N', NULL, NULL, 
    NULL, NULL, 14146, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('627', '2022', 'T21D', 'O', 2382, 
    1, 'C2020', NULL, NULL, '531122', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 14146, NULL, NULL, 
    NULL, 'PENSION IVOIRIENNE FEVRIER 2022-', NULL, NULL, '3', 
    'T', 'CREDIT', TO_DATE('06/12/2022', 'DD/MM/YYYY'), TO_DATE('21/04/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('03/01/2023 10:45:51', 'DD/MM/YYYY HH24:MI:SS'), 'NIABA', TO_DATE('03/01/2023 10:45:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'NIABA', 'ACCT242', 'N', NULL, NULL, 
    NULL, NULL, 14146, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('627', '2022', 'T21D', 'O', 2381, 
    2, 'C2020', NULL, NULL, '390303011', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 14146, '39111', '431112', 
    '501', 'PENSION IVOIRIENNE MARS 2022-', TO_DATE('06/12/2022 17:01:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, '3', 
    'T', 'DEBIT+3SPEC', TO_DATE('06/12/2022', 'DD/MM/YYYY'), TO_DATE('21/04/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('03/01/2023 10:45:52', 'DD/MM/YYYY HH24:MI:SS'), 'NIABA', TO_DATE('03/01/2023 10:45:52', 'DD/MM/YYYY HH24:MI:SS'), 
    'NIABA', 'ACCT242', 'N', NULL, NULL, 
    NULL, NULL, 14146, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('627', '2022', 'T21D', 'O', 2381, 
    1, 'C2020', NULL, NULL, '531122', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 14146, NULL, NULL, 
    NULL, 'PENSION IVOIRIENNE MARS 2022-', NULL, NULL, '3', 
    'T', 'CREDIT', TO_DATE('06/12/2022', 'DD/MM/YYYY'), TO_DATE('21/04/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('03/01/2023 10:45:52', 'DD/MM/YYYY HH24:MI:SS'), 'NIABA', TO_DATE('03/01/2023 10:45:52', 'DD/MM/YYYY HH24:MI:SS'), 
    'NIABA', 'ACCT242', 'N', NULL, NULL, 
    NULL, NULL, 14146, NULL, NULL, 
    NULL);
COMMIT;
