SET DEFINE OFF;
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1208, 
    1, 'C2020', NULL, NULL, '531122', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 19200, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'CREDIT', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:38', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 19200, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1206, 
    1, 'C2020', NULL, NULL, '531122', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 15150, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'CREDIT', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 15150, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1207, 
    1, 'C2020', NULL, NULL, '531122', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 37050, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'CREDIT', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 37050, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1208, 
    2, 'C2020', 'T2012', '339', '4413', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 19200, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'DEBIT+T', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 19200, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1206, 
    2, 'C2020', 'T2012', '339', '4413', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 15150, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'DEBIT+T', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 15150, NULL, NULL, 
    NULL);
Insert into FC_LIGNE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('649', '2024', 'T21D', 'O', 1207, 
    2, 'C2020', 'T2012', '339', '4413', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 37050, NULL, NULL, 
    NULL, 'INDEMNITE DE DEPLACEMENT COMMUNE TOUMODI-', NULL, NULL, '3', 
    'T', 'DEBIT+T', TO_DATE('27/12/2024', 'DD/MM/YYYY'), TO_DATE('27/12/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 'E000618', TO_DATE('09/01/2025 13:19:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'E000618', 'ACCT203', 'N', NULL, NULL, 
    NULL, NULL, 37050, NULL, NULL, 
    NULL);
COMMIT;
