SET DEFINE OFF;
Insert into FM_MESSAGE
   (FLG_EMIS_RECU, COD_TYP_ND, IDE_ND_EMET, IDE_MESS, COD_TYP_ND_ORIG, 
    IDE_ND_ORIG, REF_MESS, FLG_EMIS_RECU1, FLG_EMIS_RECU2, IDE_GEST, 
    FLG_PAPIER, IDE_ENV, IDE_SITE_EMET, IDE_SITE_DEST, IDE_DEPECHE, 
    COD_TYP_ND1, IDE_ND_EMET1, IDE_MESS1, COD_STATUT, COD_TYP_MESS, 
    LIBL, NUM_PRIO, COMMENTAIRE, NBR_PIECE, COD_VERSION, 
    MT_CR, MT_DB, NBR_LIGNE, NBR_DEST, DAT_CRE, 
    UTI_CRE, DAT_MAJ, UTI_MAJ, TERMINAL)
 Values
   ('E', 'P', '937', 950, 'P', 
    '937', 950, NULL, NULL, '2024', 
    'N', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, 11, 
    'Centralisation d''écritures comptables-937- R.I.F BOUAKE I', 100, NULL, 1, '1.0', 
    740720, 740720, 3, 1, TO_DATE('30/01/2025 15:08:59', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', TO_DATE('30/01/2025 15:08:59', 'DD/MM/YYYY HH24:MI:SS'), 'MES', 'MES');
COMMIT;
