SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('501', '2022', 'JODACCT', 'N', 130176, 
    1, 'C2020', NULL, NULL, '4041', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 9000000, NULL, NULL, 
    NULL, 'MDT 314018922100070 DU 26/07/2022 VRB', NULL, NULL, '5', 
    'A', 'DEBIT', TO_DATE('26/07/2022', 'DD/MM/YYYY'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('26/07/2022 16:13:10', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', TO_DATE('26/07/2022 16:13:10', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 9000000, NULL, NULL, 
    NULL);
COMMIT;
