SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('501', '2024', 'JTRANSFERT', 'N', 26703, 
    NULL, 'C2020', 'RECETTES', 'P', '205C', 
    17188, 'R', 'Transfert 205C du 21/10/24', TO_DATE('08/11/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 209, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('08/11/2024 12:39:38', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('08/11/2024 12:41:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('501', '2024', 'JTRANSFERT', 'N', 26704, 
    NULL, 'C2020', 'RECETTES', 'P', '205C', 
    17188, 'R', 'Transfert 205C du 21/10/24', TO_DATE('08/11/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 209, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('08/11/2024 12:39:38', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('08/11/2024 12:41:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('501', '2024', 'JTRANSFERT', 'N', 26705, 
    NULL, 'C2020', 'RECETTES', 'P', '205C', 
    17188, 'R', 'Transfert 205C du 21/10/24', TO_DATE('08/11/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 209, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('08/11/2024 12:39:38', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('08/11/2024 12:41:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('501', '2024', 'JTRANSFERT', 'N', 26706, 
    NULL, 'C2020', 'RECETTES', 'P', '205C', 
    17188, 'R', 'Transfert 205C du 21/10/24', TO_DATE('08/11/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 209, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('08/11/2024 12:39:38', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('08/11/2024 12:41:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('501', '2024', 'JTRANSFERT', 'N', 26707, 
    NULL, 'C2020', 'RECETTES', 'P', '205C', 
    17188, 'R', 'Transfert 205C du 21/10/24', TO_DATE('08/11/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 209, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('08/11/2024 12:39:39', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('08/11/2024 12:41:38', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
COMMIT;
