SET DEFINE OFF;
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('602C', '2024', 'JTRANSFERT', 1, 1, 
    'CREDIT', 49, '390311', 171367619, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABENGOUROU CF ABG', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:33', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:33', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 171367619);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('602C', '2024', 'JTRANSFERT', 1, 2, 
    'DEBIT', 49, '39113', 171367619, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABENGOUROU CF ABG', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:33', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:33', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 171367619);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 1, 
    'CREDIT', 49, '390311', 637054, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 ABJ CONT SOLDE CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 637054);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 2, 
    'DEBIT', 49, '39113', 637054, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 ABJ CONT SOLDE CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 637054);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 3, 
    'DEBIT', 49, '39113', 403750, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL MIN SANTE CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 403750);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 4, 
    'CREDIT', 49, '390311', 538362, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTRL ENS TECH CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:35', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 538362);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 5, 
    'DEBIT', 49, '39113', 538362, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTRL ENS TECH CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 538362);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 6, 
    'CREDIT', 49, '390311', 403750, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL MIN SANTE CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 403750);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 7, 
    'DEBIT', 49, '39113', 1550292, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL MIN INT CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 1550292);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 8, 
    'CREDIT', 49, '390311', 1550292, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL MIN INT CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 1550292);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 9, 
    'DEBIT', 49, '39113', 14401455, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL EDUC NAT CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 14401455);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 10, 
    'CREDIT', 49, '390311', 14401455, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 SSCTL EDUC NAT CF ABJ SUD', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 14401455);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 11, 
    'DEBIT', 49, '39113', 615764820, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABIDJAN SUD CF ABIDJAN', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 615764820);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('603C', '2024', 'JTRANSFERT', 2, 12, 
    'CREDIT', 49, '390311', 615764820, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABIDJAN SUD CF ABIDJAN', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 615764820);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('604C', '2024', 'JTRANSFERT', 3, 1, 
    'DEBIT', 49, '39113', 21762789, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABOISSO CF ABOISSO', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 21762789);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('604C', '2024', 'JTRANSFERT', 3, 2, 
    'CREDIT', 49, '390311', 21762789, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ABOISSO CF ABOISSO', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 21762789);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('606C', '2024', 'JTRANSFERT', 4, 1, 
    'DEBIT', 49, '39113', 18526807, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ADZOPE CF ADZOPE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:40', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:40', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 18526807);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('606C', '2024', 'JTRANSFERT', 4, 2, 
    'CREDIT', 49, '390311', 18526807, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG ADZOPE CF ADZOPE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:40', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:40', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 18526807);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('607C', '2024', 'JTRANSFERT', 5, 1, 
    'DEBIT', 49, '39113', 33266614, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG AGBOVILLE CF AGBOVILLE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:42', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 33266614);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('607C', '2024', 'JTRANSFERT', 5, 2, 
    'CREDIT', 49, '390311', 33266614, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG AGBOVILLE CF AGBOVILLE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:42', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 33266614);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('612C', '2024', 'JTRANSFERT', 6, 1, 
    'DEBIT', 49, '39113', 379130456, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BONDOUKOU CF BONDOUKOU', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:44', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:44', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 379130456);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('612C', '2024', 'JTRANSFERT', 6, 2, 
    'CREDIT', 49, '390311', 379130456, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BONDOUKOU CF BONDOUKOU', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:45', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:45', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 379130456);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('614C', '2024', 'JTRANSFERT', 7, 1, 
    'CREDIT', 49, '390311', 88250, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BOUAFLE CF BOUAFLE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:47', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 88250);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('614C', '2024', 'JTRANSFERT', 7, 2, 
    'DEBIT', 49, '39113', 88250, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BOUAFLE CF BOUAFLE', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:47', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 88250);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('615C', '2024', 'JTRANSFERT', 8, 1, 
    'DEBIT', 49, '39113', 168344216, 'D', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BOUAKE-SUD CF BOUAKE-SU', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:48', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:48', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 168344216);
Insert into IC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, IDE_ECR, IDE_LIG, 
    IDE_MODELE_LIG, IDE_TRT, IDE_CPT, MT, COD_SENS, 
    SPEC1, SPEC2, SPEC3, COD_REF_PIECE, IDE_TIERS, 
    DAT_REF, OBSERV, IDE_ORDO, COD_BUD, IDE_LIG_EXEC, 
    IDE_OPE, COD_TYP_BUD, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, IDE_PLAN_AUX, IDE_CPT_AUX, IDE_DEVISE, 
    VAL_TAUX, MT_DEV)
 Values
   ('615C', '2024', 'JTRANSFERT', 8, 2, 
    'CREDIT', 49, '390311', 168344216, 'C', 
    NULL, NULL, NULL, NULL, NULL, 
    TO_DATE('26/07/2024', 'DD/MM/YYYY'), 'T59 SAL JUILLET 24 TG BOUAKE-SUD CF BOUAKE-SU', NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('06/08/2024 13:04:49', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('06/08/2024 13:04:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL, 'XOF', 
    1, 168344216);
COMMIT;
