SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 21, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:56', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:56', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 20, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:54', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:54', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 19, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:51', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 18, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:49', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 17, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:46', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:46', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 16, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:43', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:43', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 15, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 14, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 13, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:34', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:34', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 12, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 16:07:31', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 16:07:31', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 11, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:42:47', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:42:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 10, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:42:45', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:42:45', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 9, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:42:42', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:42:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 8, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:42:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:42:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 7, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:22:35', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:22:35', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 6, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:22:32', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:22:32', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 5, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 15:22:30', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 15:22:30', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 4, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 3, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 2, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:33', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:33', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('502', '2025', 'TREP', 'O', 1, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:17', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:30', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:30', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
COMMIT;
