SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('3000', '2025', 'TREP', 'O', 1, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:03', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:04', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:04', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('3000', '2025', 'TREP', 'O', 2, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:03', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:06', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:06', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('3000', '2025', 'TREP', 'O', 3, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:03', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:14', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('3000', '2025', 'TREP', 'O', 4, 
    TO_DATE('02/01/2025', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2024', TO_DATE('09/01/2025 14:30:03', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2025', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('09/01/2025 14:30:16', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('09/01/2025 14:30:16', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
COMMIT;
