SET DEFINE OFF;
Insert into FC_LIG_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('510', '2024', 'JODPGSP', 'N', 415, 
    1, 'C2020', NULL, NULL, '4211', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 90949313, NULL, NULL, 
    NULL, 'MDT 314010624100385 DU 11/07/2024 VIR', NULL, NULL, '1', 
    'A', 'DEBIT', TO_DATE('11/07/2024', 'DD/MM/YYYY'), TO_DATE('11/07/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
Insert into FC_LIG_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('510', '2024', 'JODPGSP', 'N', 415, 
    2, 'C2020', NULL, 'TIER A RENSEIGNER', '4667106', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 90949313, NULL, NULL, 
    NULL, 'MDT 314010624100385 DU 11/07/2024 VIR', NULL, NULL, '1', 
    'A', 'CREDIT+T', TO_DATE('11/07/2024', 'DD/MM/YYYY'), TO_DATE('11/07/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
Insert into FC_LIG_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('510', '2024', 'JODPGSP', 'N', 416, 
    1, 'C2020', NULL, NULL, '4211', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 30000, NULL, NULL, 
    NULL, 'MDT 314010624100386 DU 11/07/2024 VIR', NULL, NULL, '1', 
    'A', 'DEBIT', TO_DATE('11/07/2024', 'DD/MM/YYYY'), TO_DATE('11/07/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
Insert into FC_LIG_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('510', '2024', 'JODPGSP', 'N', 416, 
    2, 'C2020', NULL, 'TIER A RENSEIGNER', '4667106', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 30000, NULL, NULL, 
    NULL, 'MDT 314010624100386 DU 11/07/2024 VIR', NULL, NULL, '1', 
    'A', 'CREDIT+T', TO_DATE('11/07/2024', 'DD/MM/YYYY'), TO_DATE('11/07/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL);
COMMIT;
