SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('504', '2024', 'T23', 'N', 11, 
    4, 'C2020', NULL, NULL, '39112', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', -34500, NULL, '4663154', 
    '502', 'RECTIFICATION D''ECRITURE N°9996 RETENUE 314010524100220 KONE BINTOU', NULL, NULL, 'RECTIFICATIONS', 
    'A', 'CREDIT 39112', NULL, TO_DATE('31/12/2024 12:00:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, TO_DATE('04/02/2025 16:27:15', 'DD/MM/YYYY HH24:MI:SS'), '873533K', TO_DATE('11/02/2025 17:06:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASTERPRO', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, -34500, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('504', '2024', 'T23', 'N', 11, 
    1, 'C2020', NULL, NULL, '401121', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', -34500, NULL, NULL, 
    NULL, 'RECTIFICATION D''ECRITURE N°9996 RETENUE 314010524100220 KONE BINTOU', NULL, NULL, 'RECTIFICATIONS', 
    'A', 'DEBIT', NULL, TO_DATE('31/12/2024 12:00:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, TO_DATE('04/02/2025 16:27:15', 'DD/MM/YYYY HH24:MI:SS'), '873533K', TO_DATE('11/02/2025 17:06:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASTERPRO', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, -34500, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('504', '2024', 'T23', 'N', 11, 
    3, 'C2020', NULL, NULL, '4751153', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', -34500, NULL, NULL, 
    NULL, 'RECTIFICATION D''ECRITURE N°9996 RETENUE 314010524100220 KONE BINTOU', NULL, NULL, 'RECTIFICATIONS', 
    'A', 'DEBIT', NULL, TO_DATE('31/12/2024 12:00:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, TO_DATE('04/02/2025 16:27:15', 'DD/MM/YYYY HH24:MI:SS'), '873533K', TO_DATE('11/02/2025 17:06:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASTERPRO', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, -34500, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('504', '2024', 'T23', 'N', 11, 
    2, 'C2020', NULL, NULL, '4751153', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', -34500, NULL, NULL, 
    NULL, 'RECTIFICATION D''ECRITURE N° 9996  RETENUE 314010524100220 KONE BINTOU', NULL, NULL, 'RECTIFICATIONS', 
    'A', 'CREDIT', NULL, TO_DATE('31/12/2024 12:00:00', 'DD/MM/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, TO_DATE('04/02/2025 16:27:15', 'DD/MM/YYYY HH24:MI:SS'), '873533K', TO_DATE('11/02/2025 17:06:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ASTERPRO', 'unknown', 'N', NULL, NULL, 
    NULL, NULL, -34500, NULL, NULL, 
    NULL);
COMMIT;
