SET DEFINE OFF;
Insert into FM_MESSAGE
   (FLG_EMIS_RECU, COD_TYP_ND, IDE_ND_EMET, IDE_MESS, COD_TYP_ND_ORIG, 
    IDE_ND_ORIG, REF_MESS, FLG_EMIS_RECU1, FLG_EMIS_RECU2, IDE_GEST, 
    FLG_PAPIER, IDE_ENV, IDE_SITE_EMET, IDE_SITE_DEST, IDE_DEPECHE, 
    COD_TYP_ND1, IDE_ND_EMET1, IDE_MESS1, COD_STATUT, COD_TYP_MESS, 
    LIBL, NUM_PRIO, COMMENTAIRE, NBR_PIECE, COD_VERSION, 
    MT_CR, MT_DB, NBR_LIGNE, NBR_DEST, DAT_CRE, 
    UTI_CRE, DAT_MAJ, UTI_MAJ, TERMINAL)
 Values
   ('R', 'P', '3092', 365, 'P', 
    '3092', 365, NULL, NULL, '2024', 
    'N', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, 24, 
    'CUT-PAIEMENT EFFECTIF DU 09/08/2024', 100, NULL, 6, '1.0', 
    900000, 900000, 0, 0, TO_DATE('28/01/2025 15:17:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', TO_DATE('28/01/2025 15:18:17', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', 'UNKNOWN');
COMMIT;
