SET DEFINE OFF;
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3028', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3035', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3070', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3083', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3085', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3092', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('633', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('676', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('691', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('708', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3009', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3012', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3061', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3078', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3092', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3103', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('508', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('512', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('634', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('683', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('08/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('509', TO_DATE('14/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3069', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3102', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'RET');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('508', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'OPP');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('686', TO_DATE('01/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('616', TO_DATE('05/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('06/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('512', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('503', TO_DATE('08/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('659', TO_DATE('08/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3070', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3074', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3093', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3104', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('511', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('6008', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('629', TO_DATE('13/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('509', TO_DATE('14/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3039', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3041', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3042', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3043', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3044', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3046', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3048', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3049', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3054', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3055', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3057', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3060', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3061', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3064', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3066', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3067', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3069', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3070', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3075', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3078', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3079', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3080', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3081', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3082', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3084', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3085', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3086', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3088', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3091', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3092', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3094', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3097', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3098', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3099', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3102', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3103', TO_DATE('19/12/2022', 'DD/MM/YYYY'), 'PAIE');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3021', TO_DATE('02/12/2022', 'DD/MM/YYYY'), 'REJ');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('3070', TO_DATE('02/12/2022', 'DD/MM/YYYY'), 'REJ');
Insert into CUT_TRANSFERT_BALAIS_CTL
   (TRANSF_PC_CODE, TRANSF_DATE, SOURCE)
 Values
   ('514', TO_DATE('07/12/2022', 'DD/MM/YYYY'), 'REJ');
COMMIT;
