SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3031', '2022', 'T29EPN', 'N', 446, 
    1, 'C2020', NULL, NULL, '51511142', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 808600, NULL, NULL, 
    NULL, 'DEGAGEMENT DE LA CAISSE DU05/08/2022', NULL, NULL, '1', 
    'A', 'C 51511142', NULL, TO_DATE('09/08/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/08/2022 14:18:11', 'DD/MM/YYYY HH24:MI:SS'), 'C256314', TO_DATE('09/08/2022 14:18:11', 'DD/MM/YYYY HH24:MI:SS'), 
    'C256314', 'SRV-CTX-02', 'N', NULL, NULL, 
    NULL, NULL, 808600, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('3031', '2022', 'T29EPN', 'N', 446, 
    2, 'C2020', NULL, NULL, '581117', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 808600, NULL, NULL, 
    NULL, 'DEGAGEMENT DE LA CAISSE DU05/08/2022', NULL, NULL, '1', 
    'A', 'D 581117', NULL, TO_DATE('09/08/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('09/08/2022 14:18:12', 'DD/MM/YYYY HH24:MI:SS'), 'C256314', TO_DATE('09/08/2022 14:18:12', 'DD/MM/YYYY HH24:MI:SS'), 
    'C256314', 'SRV-CTX-02', 'N', NULL, NULL, 
    NULL, NULL, 808600, NULL, NULL, 
    NULL);
COMMIT;
