select * from fc_transfert_mer
--update fc_transfert_mer set ide_mess = 271935
where dap_pct_code = '501'
and ead_exe = '2022'
--and ead_num_acte =  '314018922100070'
and rgl_journee = '26/07/2022';

/*
INSERT INTO FC_ECRITURE@lkast(IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, IDE_MESS, FLG_EMIS_RECU,LIBN, DAT_SAISIE, DAT_ECR, COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, IDE_PIECE, COD_TYP_PIECE)
 SELECT IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, IDE_MESS, FLG_EMIS_RECU,LIBN, DAT_SAISIE, DAT_ECR, COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, IDE_PIECE, COD_TYP_PIECE
FROM FC_ECRI_MER@lkast WHERE ide_poste = '501' AND ide_gest = '2022' ;

 INSERT INTO FC_LIGNE @lkast (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, COD_BUD, COD_BE,MT_DEV)
 SELECT  IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, COD_BUD, COD_BE ,MT
 FROM FC_LIG_MER@lkast WHERE ide_poste = '501' AND ide_gest = '2022' ;
 */