SET DEFINE OFF;
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130061, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10089', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130062, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10092', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130063, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10083', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130064, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10088', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130065, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10081', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130066, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10087', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130067, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10090', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130068, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10093', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130069, 
    NULL, 'C2020', '5', 'P', '501', 
    271916, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10082', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130069, 
    NULL, 'C2020', '5', 'P', '501', 
    271913, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10082', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130070, 
    NULL, 'C2020', '5', 'P', '501', 
    271913, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10085', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130059, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:20', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10084', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130060, 
    NULL, 'C2020', '5', 'P', '501', 
    271915, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:21:21', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10086', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
COMMIT;
