SET DEFINE OFF;
Insert into FC_ECRI_MER
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_PEC)
 Values
   ('501', '2022', 'JODACCT', 'N', 130073, 
    NULL, 'C2020', '5', 'P', '501', 
    271917, 'R', 'TRANSFERT MER ASTER  du 26/07/2022', TO_DATE('26/07/2022 15:30:28', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('26/07/2022', 'DD/MM/YYYY'), 
    'SA', NULL, NULL, NULL, NULL, 
    'PHS10082', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL);
COMMIT;
