INSERT INTO T_TRANSFERT_BIS_N_WEB_BIS
SELECT * FROM T_TRANSFERT_BIS_N
WHERE JOURNEE = '&&date_oper';

INSERT INTO T_TRANSFERT_BIS_BANQ_N_WEB
SELECT * FROM T_TRANSFERT_BIS_BANQ_N
WHERE JOURNEE = '&&date_oper';

INSERT INTO T_TRANS_BIS_ORDRE_OP1_AG_N_WEB
SELECT * FROM T_TRANSFERT_BIS_ORDRE_OP1_AG_N
WHERE JOURNEE = '&&date_oper';

INSERT INTO T_TRANS_BIS_ORDRE_OP2_AG_N_WEB
SELECT * FROM T_TRANSFERT_BIS_ORDRE_OP2_AG_N
WHERE JOURNEE = '&&date_oper';

INSERT INTO T_TRANS_BCEAO_BQ_SG_WEB
SELECT * FROM T_TRANS_BCEAO_BQ_SG
WHERE JOURNEE = '&&date_oper';

INSERT INTO T_LJ_OP_BQ_COMPENS_SG_WEB
SELECT * FROM T_LJ_OP_BQ_COMPENS_SG
WHERE JOURNEE = '&&date_oper';

UPDATE T_TRANSFERT_BIS_N_WEB_BIS SET STATUT = 'S'
--SELECT * FROM T_TRANSFERT_BIS_N_WEB_BIS
WHERE JOURNEE = '&&date_oper'
AND STATUT <> 'S';

UPDATE T_TRANSFERT_BIS_BANQ_N_WEB SET STATUT = 'S'
--SELECT * FROM T_TRANSFERT_BIS_BANQ_N_WEB
WHERE JOURNEE = '&&date_oper'
AND STATUT <> 'S';

UPDATE T_TRANS_BIS_ORDRE_OP1_AG_N_WEB SET STATUT = 'S'
--SELECT * FROM T_TRANS_BIS_ORDRE_OP1_AG_N_WEB
WHERE JOURNEE = '&&date_oper'
AND EMETTEUR = '01004'
AND STATUT <> 'S';

UPDATE T_TRANS_BIS_ORDRE_OP2_AG_N_WEB SET STATUT = 'S'
--SELECT * FROM T_TRANS_BIS_ORDRE_OP2_AG_N_WEB
WHERE JOURNEE = '&&date_oper'
AND EMETTEUR = '01004'
AND STATUT <> 'S';

UPDATE T_TRANS_BCEAO_BQ_SG_WEB SET STATUT = 'S'
--SELECT * FROM T_TRANS_BCEAO_BQ_SG_WEB
WHERE JOURNEE = '&&date_oper'
AND STATUT <> 'S';

UPDATE T_LJ_OP_BQ_COMPENS_SG_WEB SET STATUT = 'S'
--SELECT * FROM T_LJ_OP_BQ_COMPENS_SG_WEB
WHERE JOURNEE = '&&date_oper'
AND STATUT <> 'S';



---------------------------------------------------------------------------------

SELECT * FROM T_TRANSFERT_BIS_N_WEB_BIS
WHERE JOURNEE = '&&date_oper'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

SELECT * FROM T_TRANSFERT_BIS_BANQ_N_WEB
WHERE JOURNEE = '&&date_oper'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

SELECT * FROM T_TRANS_BIS_ORDRE_OP1_AG_N_WEB
WHERE JOURNEE = '&&date_oper'
--AND EMETTEUR = '01004'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

SELECT * FROM T_TRANS_BIS_ORDRE_OP2_AG_N_WEB
WHERE JOURNEE = '&&date_oper'
--AND EMETTEUR = '01004'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

SELECT * FROM T_TRANSFERT_BIS_ORDRE_OP2_AG_N
WHERE JOURNEE = '&&date_oper'
AND EMETTEUR = '01004';

SELECT * FROM T_TRANS_BCEAO_BQ_SG_WEB
WHERE JOURNEE = '&&date_oper'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

SELECT * FROM T_LJ_OP_BQ_COMPENS_SG_WEB
WHERE JOURNEE = '&&date_oper'
ORDER BY EMETTEUR, ECRITURE, MONTANT, SENS
;

