------- CONTROLE --------

SELECT * FROM T_OP_TRANSFERTS_SIEGE_NDIR
WHERE JOURNEE='07/03/2022'
--AND emetteur='01002'
;

SELECT * FROM T_TRANS_BCEAO_BQ_SG
WHERE JOURNEE='07/03/2022'
;

------  -------

SELECT TYPE, EMETTEUR,JOURNEE||'-'||LIBELLE LIBELLE,GESTION, MONTANT, PRIORITE,JOURNEE , SCHEMA, JOURNAL , STATUT, COMPTE, SENS, SYSDATE DAT_TRANSF,NUM_ECR,GROUPE,NATOP,CODENATOP
FROM ORAS.TB_INFO_TRANSF_OP_TRANS_SI
WHERE JOURNEE='31/03/2021'
AND EMETTEUR='01530'
;

-------- CHARGEMENT ---------

INSERT INTO ORAS.T_OP_TRANSFERTS_SIEGE_NDIR(TYPE,EMETTEUR,LIBELLE,GESTION,MONTANT,PRIORITE ,JOURNEE,SCHEMA,JOURNAL,STATUT,COMPTE,SENS,DAT_TRANSF,DESTINATAIRE,ECRITURE,GROUPE,NATOP,CODENATOP)
SELECT TYPE, EMETTEUR,JOURNEE||'-'||LIBELLE LIBELLE,GESTION, MONTANT, PRIORITE,JOURNEE , SCHEMA, JOURNAL , STATUT, COMPTE, SENS, SYSDATE DAT_TRANSF,SPEC,NUM_ECR,GROUPE,NATOP,CODENATOP
FROM ORAS.VB_INFO_TRANSF_OP_TRANS_SI
WHERE JOURNEE='31/03/2021'
AND EMETTEUR='01530'
;

------------ CHARGEMENT DES STATUT ---------------

UPDATE  T_OP_TRANSFERTS_SIEGE_NDIR
SET STATUT='S'
WHERE  JOURNEE='28/09/2021'
and emetteur='01511'