-----------DECOMPOSITION DE LA PROCEDURE ORAS.P_MAJ_DONNEES_ORAS_NEW ('17/10/2025' IN DATE )------------
------NB REMPLACER '17/10/2025' par la journée ---------------'17/10/2025'='17/10/2025'
----SELECTIONNER TOUTES LES PROCEDURES ET EXECUTER AVEC LE BOUTON EXECUTE AS a script
alter session set nls_date_format = 'DD/MM/YYYY';

EXEC ORAS.P_Maj_Chqencma_NEW('17/10/2025');
EXEC  ORAS.P_Maj_Librop_NEW('17/10/2025');
EXEC ORAS.P_Maj_Virchac_NEW('17/10/2025');
EXEC  ORAS.P_MAJ_VIRCHAC_INFO('17/10/2025');
EXEC ORAS.P_Maj_Virint_NEW('17/10/2025');
EXEC ORAS.P_Maj_Pers_NEW ;
EXEC ORAS.P_Maj_Codopsc_NEW;
EXEC ORAS.P_Maj_Cli_NEW ;
EXEC ORAS.P_Maj_Cpt_NEW ;
EXEC  ORAS.P_Maj_Cpt_Posdev;
EXEC ORAS.P_Maj_T_Virmulta_All;
EXEC  ORAS.P_Maj_Guichet_Oras_NEW('17/10/2025');
EXEC  ORAS.P_Maj_Mvtc_Last_NEW('17/10/2025');
EXEC ORAS.P_INS_FX5Y8;
EXEC ORAS.P_MAJ_AG_CAIS_CSERV_NEW('17/10/2025');
EXEC ORAS.P_Maj_Ncglib_Insert;
EXEC ORAS.P_INS_CPT;
EXEC ORAS.P_MAJ_CPT_NCG_INFO ;
EXEC ORAS.P_MAJ_CODE_AGENCE;
EXEC ORAS.P_MAJ_COMPTE_INFOS;
EXEC ORAS.P_MAJ_CPT_AGENCE;
EXEC ORAS.P_Maj_Codopsc_Diff ;
EXEC ORAS.P_Maj_Agence_Mvtc_Date('17/10/2025');
EXEC ORAS.P_Maj_Stat_Si('17/10/2025');
EXEC ORAS.P_Insert_Dep_Cli_Credit_Ag_Bis('17/10/2025');
EXEC ORAS.P_Insert_Dep_Cli_Debit_Ag_Bis('17/10/2025');
EXEC ORAS.P_Insert_Rem_Cli_Credit_Ag_Bis('17/10/2025');
EXEC ORAS.P_Insert_Rem_Cli_Debit_Ag_Bis ('17/10/2025');
EXEC ORAS.P_Insert_Det_Op_Int_Deb_Ag('17/10/2025');
EXEC ORAS.P_Insert_Det_Op_Int_Cred_Ag('17/10/2025');
EXEC ORAS.P_INSERT_RET_DEPL_GLOB_ENC_BIS('17/10/2025');
EXEC ORAS.P_Insert_Tab_Recap_Nraire('17/10/2025');
EXEC ORAS.P_INSERT_TP_REVERS_FRAIS_ORAS  ;
EXEC ORAS.P_INSERT_TP_COM_DDE_GIM_ORAS  ;
EXEC ORAS.P_INSERT_TP_COM_PERCU_RET_ORAS  ;
EXEC ORAS.P_INSERT_TP_COM_DIVERS_ORAS ;
EXEC ORAS.P_INSERT_TP_ANN_COM_RET_ORAS ;
EXEC ORAS.P_INSERT_TP_TPS_COM_RET_DEPL ;
EXEC ORAS.P_INSERT_TP_COM_REJET_CHQ ;
EXEC ORAS.P_INSERT_TP_TPS_COM_OPP_CHQ ;
EXEC ORAS.P_INS_TP_TPE_BCAIRE_AG_DEP;
EXEC ORAS.P_INS_TP_TPS_COM_RET_DEPL_NEW;

--------EXECUTER ENSUITE LA 2eme Procédure ORAS.P_MAJ_ORAS_ORION_NEW_XXX en modifiant DATOPER par la journée
---Exemple CURSOR C_DATE IS SELECT DISTINCT DATOPER FROM  bdt.MVTC@ORION.WORLD where DATOPER >='05/01/2021' AND DATOPER='17/10/2025';

alter session set nls_date_format = 'DD/MM/YYYY';
EXEC ORAS.P_MAJ_ORAS_ORION_NEW_XXX;
