SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('506', '2022', 'JODPGDP', 'N', 13175, 
    1, 'C2020', NULL, NULL, '40131', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', -3068136941, NULL, NULL, 
    NULL, 'ANNULATION DE MER DEPUIS PECMER', NULL, NULL, '11', 
    'A', 'DEBIT', TO_DATE('15/09/2022', 'DD/MM/YYYY'), NULL, NULL, 
    NULL, NULL, TO_DATE('28/02/2023 18:46:25', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', TO_DATE('28/02/2023 18:46:25', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, -3068136941, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('506', '2022', 'JODPGDP', 'N', 13175, 
    2, 'C2020', NULL, NULL, '5152111', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', -3068136941, NULL, NULL, 
    NULL, 'ANNULATION DE MER DEPUIS PECMER', NULL, NULL, '11', 
    'A', 'CREDIT', TO_DATE('15/09/2022', 'DD/MM/YYYY'), NULL, NULL, 
    NULL, NULL, TO_DATE('28/02/2023 18:46:25', 'DD/MM/YYYY HH24:MI:SS'), 'PIAF_ADM', TO_DATE('28/02/2023 18:46:25', 'DD/MM/YYYY HH24:MI:SS'), 
    'PIAF_ADM', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, -3068136941, NULL, NULL, 
    NULL);
COMMIT;
