SET DEFINE OFF;
Insert into FC_ECRITURE_DELETE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR)
 Values
   ('506', '2022', 'TREP', 'O', 103, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:05:52', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:13:59', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:13:59', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL);
COMMIT;
