SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 3, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:32', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:32', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 4, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:34', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:34', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 5, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 6, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:40', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:40', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 1, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:26', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:26', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 2, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:29', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:29', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 7, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:42', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 8, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:44', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:44', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 9, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:46', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:46', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 10, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:48', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:48', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 11, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:49', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 12, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:51', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 13, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:53', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:53', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 14, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:55', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 15, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:56', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:56', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 16, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:03:58', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:03:58', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 17, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:00', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:00', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 18, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:02', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:02', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 19, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:05', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:05', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 20, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:07', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:07', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 21, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:08', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:08', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 22, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:11', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:11', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 23, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:12', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:12', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 24, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:14', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:14', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 25, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:16', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:16', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 26, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:17', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:17', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 27, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:22', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:22', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 28, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:24', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:24', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 29, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:32', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:32', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 30, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:34', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:34', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 31, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:36', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:36', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 32, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:37', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:37', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 33, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:39', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:39', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 34, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:40', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:40', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 35, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:42', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:42', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 36, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:44', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:44', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 37, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:46', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:46', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 38, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:47', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:47', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 39, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:49', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 40, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:04:51', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:04:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 41, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:05:49', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:05:49', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 42, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:05:50', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:05:50', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('504', '2022', 'TREP', 'O', 43, 
    TO_DATE('02/01/2022', 'DD/MM/YYYY'), 'C2020', 'REP PARTIELLE', NULL, NULL, 
    NULL, NULL, 'Ecriture BE partielle de la gestion 2021', TO_DATE('23/06/2023 19:03:22', 'DD/MM/YYYY HH24:MI:SS'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 
    'CO', NULL, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('23/06/2023 19:05:51', 'DD/MM/YYYY HH24:MI:SS'), 'ACCTDBA', TO_DATE('23/06/2023 19:05:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
COMMIT;
