SET DEFINE OFF;
Insert into RM_POSTE
   (IDE_POSTE, COD_TYP_ND, IDE_POSTE_CENTRA, IDE_POSTE_ADM, IDE_TYP_POSTE, 
    VAR_TIERS, FLG_CF, FLG_CENTRAL, FLG_PIAF, FLG_RF, 
    FLG_CPTA_MAX, FLG_CPTA_PRINC, FLG_CAD, FLG_CAR, DAT_DIFF, 
    DAT_DVAL, DES_PARC, FLG_NOMEN, DAT_CRE, UTI_CRE, 
    DAT_MAJ, UTI_MAJ, TERMINAL, IDE_DEVISE)
 Values
   ('889', 'P', '603C', '501C', 'TP', 
    'T2012', 'N', 'N', 'O', 'N', 
    'N', 'N', 'N', 'N', NULL, 
    NULL, NULL, 'N', TO_DATE('11/12/2023 08:36:08', 'DD/MM/YYYY HH24:MI:SS'), 'E459144', 
    TO_DATE('03/01/2024 08:45:38', 'DD/MM/YYYY HH24:MI:SS'), 'E459144', 'ASTER', '12');
COMMIT;
