SET DEFINE OFF;
Insert into RM_POSTE
   (IDE_POSTE, COD_TYP_ND, IDE_POSTE_CENTRA, IDE_POSTE_ADM, IDE_TYP_POSTE, 
    VAR_TIERS, FLG_CF, FLG_CENTRAL, FLG_PIAF, FLG_RF, 
    FLG_CPTA_MAX, FLG_CPTA_PRINC, FLG_CAD, FLG_CAR, DAT_DIFF, 
    DAT_DVAL, DES_PARC, FLG_NOMEN, DAT_CRE, UTI_CRE, 
    DAT_MAJ, UTI_MAJ, TERMINAL, IDE_DEVISE)
 Values
   ('3134', 'P', '510C', '501C', 'EPN', 
    'T2012', 'N', 'N', 'O', 'N', 
    'N', 'N', 'N', 'N', NULL, 
    NULL, NULL, 'N', TO_DATE('10/09/2024 08:13:15', 'DD/MM/YYYY HH24:MI:SS'), 'P849230', 
    TO_DATE('10/09/2024 08:14:10', 'DD/MM/YYYY HH24:MI:SS'), 'P849230', 'RDS-ASTER', '12');
COMMIT;
