SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('7027', '2022', 'T10BIS', 'N', 41, 
    1, 'C2020', NULL, NULL, '531222', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 35000, NULL, NULL, 
    NULL, 'PRIME SESSION CONSEIL REGIONAL SAN PEDRO 0710', NULL, NULL, '5', 
    'T', 'CREDIT', NULL, TO_DATE('07/10/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('10/10/2022 07:49:01', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('10/10/2022 07:49:01', 'DD/MM/YYYY HH24:MI:SS'), 
    'SYGACUT', 'UNKNOWN', 'N', NULL, NULL, 
    NULL, NULL, 35000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('7027', '2022', 'T10BIS', 'N', 41, 
    2, 'C2020', 'T2012', '7027', '4411', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 35000, NULL, NULL, 
    NULL, 'PRIME SESSION CONSEIL REGIONAL SAN PEDRO 0710', NULL, NULL, '5', 
    'T', 'DEBIT+T', NULL, TO_DATE('07/10/2022', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('10/10/2022 07:49:01', 'DD/MM/YYYY HH24:MI:SS'), 'SYGACUT', TO_DATE('10/10/2022 09:33:46', 'DD/MM/YYYY HH24:MI:SS'), 
    'U297615', 'SVR_RDS', 'N', NULL, NULL, 
    NULL, NULL, 35000, NULL, NULL, 
    NULL);
COMMIT;
