SET DEFINE OFF;
Insert into FC_ECRITURE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    DAT_JC, VAR_CPTA, IDE_SCHEMA, COD_TYP_ND, IDE_ND_EMET, 
    IDE_MESS, FLG_EMIS_RECU, LIBN, DAT_SAISIE, DAT_ECR, 
    COD_STATUT, IDE_TRT, FLG_ECR_SOMME, COD_BUD, IDE_ORDO, 
    IDE_PIECE, COD_TYP_PIECE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, DAT_VALEUR, NUMSEQ)
 Values
   ('503', '2024', 'JTRANSFERT', 'N', 4054, 
    NULL, 'C2020', 'DEPENSES', 'P', '451C', 
    753, 'R', 'Transfert 451C du 31/05/24', TO_DATE('13/06/2024', 'DD/MM/YYYY'), NULL, 
    'AC', 11, NULL, NULL, NULL, 
    NULL, NULL, TO_DATE('13/06/2024 09:51:40', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2024 09:53:19', 'DD/MM/YYYY HH24:MI:SS'), 
    'ACCTDBA', 'UNKNOWN', NULL, NULL);
COMMIT;
