SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('503', '2024', 'JTRANSFERT', 'N', 4054, 
    1, 'C2020', NULL, NULL, '39111', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', -8175192, NULL, NULL, 
    NULL, 'RECTIFICATION COMPTABLE A23 DU 29/04/2024', NULL, NULL, 'DEPENSES', 
    'A', 'CREDIT', NULL, TO_DATE('31/05/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, -8175192, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('503', '2024', 'JTRANSFERT', 'N', 4054, 
    2, 'C2020', NULL, NULL, '47012106', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 8175192, NULL, NULL, 
    NULL, NULL, NULL, NULL, 'DEPENSES', 
    'A', 'DEBIT', NULL, TO_DATE('31/05/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, 8175192, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('503', '2024', 'JTRANSFERT', 'N', 4054, 
    3, 'C2020', NULL, NULL, '39111', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 8175192, NULL, NULL, 
    NULL, NULL, NULL, NULL, 'DEPENSES', 
    'A', 'CREDIT', NULL, TO_DATE('31/05/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, 8175192, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('503', '2024', 'JTRANSFERT', 'N', 4054, 
    4, 'C2020', NULL, NULL, '47012106', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', -8175192, NULL, NULL, 
    NULL, 'RECTIFICATION COMPTABLE A23 DU 29/04/2024', NULL, NULL, 'DEPENSES', 
    'A', 'DEBIT', NULL, TO_DATE('31/05/2024', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 'MES', TO_DATE('13/06/2024 09:51:41', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'UNKNOWN', 'N', NULL, NULL, 
    'XOF', 1, -8175192, NULL, NULL, 
    NULL);
COMMIT;
