SET DEFINE OFF;
Insert into T_PRECOMPTE
   (PREC_NUM, PREC_MONT, PREC_DATE, PREC_DATE_PREC, PREC_STATUT, 
    PREC_CP_MATRIC, PREC_CT_CODE, PREC_CODPC, PREC_CODCRE, PREC_ECRIT, 
    PREC_BUDG, PREC_INDEM, PREC_FIN, PREC_CODE_IMP, PREC_STATUT1, 
    PREC_MONT_SOLD, PREC_NUMCHQ, PREC_DATCHQ, PREC_BANQ, DATE_CHARG, 
    PREC_SOURCE, SOURCES, PREC_STAT_DEVERS_ASTER, PREC_USER_DEVERS_ASTER, PREC_DATE_DEVERS_ASTER, 
    PREC_CP_NOMPRE)
 Values
   ('11/2022-3', 1500000, TO_DATE('01/11/2022', 'DD/MM/YYYY'), NULL, NULL, 
    '239613F', '02/2006-1022', NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    1500000, '5877334', TO_DATE('08/11/2022', 'DD/MM/YYYY'), 'tresor public', NULL, 
    'CHEQUE', NULL, NULL, NULL, NULL, 
    NULL);
COMMIT;
