--------------------- -----------------------------

DROP TABLE CGST.BGFG_ORD_CPT CASCADE CONSTRAINTS;

CREATE TABLE CGST.BGFG_ORD_CPT
(
  ORDRE     NUMBER(15),
  IDE_CPT   VARCHAR2(15 BYTE),
  LIBN      VARCHAR2(30 BYTE),
  FLG_BGCT  VARCHAR2(1 BYTE),
  FLG_CGAF  VARCHAR2(1 BYTE),
  VAR_CPTA  VARCHAR2(5 BYTE)
)
TABLESPACE ASTER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON CGST.BGFG_ORD_CPT TO PUBLIC;



--------------------- -----------------------------


DROP TABLE CGST.DELEG_CREDIT_TMP CASCADE CONSTRAINTS;

CREATE TABLE CGST.DELEG_CREDIT_TMP
(
  NOM_SERVICE  VARCHAR2(30 BYTE),
  IDE_CPT      VARCHAR2(15 BYTE),
  LIBL         VARCHAR2(255 BYTE),
  FLUX_DEBIT   NUMBER(18,3),
  FLUX_CREDIT  NUMBER(18,3),
  V_UUID       VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON CGST.DELEG_CREDIT_TMP TO PUBLIC;

--------------------- -----------------------------

DROP TABLE CGST.ETAT_CGAF_BGCT_AC CASCADE CONSTRAINTS;

CREATE TABLE CGST.ETAT_CGAF_BGCT_AC
(
  IDE_CPT  VARCHAR2(15 BYTE),
  BE_D     NUMBER,
  BE_C     NUMBER,
  OA_D     NUMBER,
  OA_C     NUMBER,
  SA_D     NUMBER,
  SA_C     NUMBER,
  OFAI_D   NUMBER,
  OFAI_C   NUMBER,
  BS_D     NUMBER,
  BS_C     NUMBER,
  GRAS     CHAR(1 BYTE),
  SID      NUMBER(5),
  UUID     VARCHAR2(50 BYTE)
)
TABLESPACE ASTER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGCT_AC TO ALJ;

GRANT SELECT ON CGST.ETAT_CGAF_BGCT_AC TO PIAF_CONSULT;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGCT_AC TO PIAF_UTIL;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGCT_AC TO PUBLIC;



--------------------- -----------------------------

DROP TABLE CGST.ETAT_CGAF_BGFG_AC CASCADE CONSTRAINTS;

CREATE TABLE CGST.ETAT_CGAF_BGFG_AC
(
  IDE_POSTE  VARCHAR2(15 BYTE)                  NOT NULL,
  IDE_CPT    VARCHAR2(15 BYTE),
  BE_D       NUMBER(18,3),
  BE_C       NUMBER(18,3),
  OA_D       NUMBER(18,3),
  OA_C       NUMBER(18,3),
  SA_D       NUMBER(18,3),
  SA_C       NUMBER(18,3),
  OFAI_D     NUMBER(18,3),
  OFAI_C     NUMBER(18,3),
  BS_D       NUMBER(18,3),
  BS_C       NUMBER(18,3)
)
TABLESPACE ASTER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGFG_AC TO PUBLIC;


--------------------- -----------------------------

DROP TABLE CGST.ETAT_CGAF_BGFG_TMP_AC CASCADE CONSTRAINTS;

CREATE TABLE CGST.ETAT_CGAF_BGFG_TMP_AC
(
  IDE_CPT  VARCHAR2(15 BYTE),
  BE_D     NUMBER(18,3),
  BE_C     NUMBER(18,3),
  OA_D     NUMBER(18,3),
  OA_C     NUMBER(18,3),
  SA_D     NUMBER(18,3),
  SA_C     NUMBER(18,3),
  OFAI_D   NUMBER(18,3),
  OFAI_C   NUMBER(18,3),
  BS_D     NUMBER(18,3),
  BS_C     NUMBER(18,3),
  SID      NUMBER(5),
  UUID     VARCHAR2(50 BYTE)
)
TABLESPACE ASTER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX CGST.INDX_SID_TMP ON CGST.ETAT_CGAF_BGFG_TMP_AC
(UUID)
LOGGING
TABLESPACE ASTER_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGFG_TMP_AC TO ALJ;

GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_BGFG_TMP_AC TO PUBLIC;



--------------------- -----------------------------

DROP TABLE CGST.ETAT_CGAF_CGAF_AC CASCADE CONSTRAINTS;

CREATE TABLE CGST.ETAT_CGAF_CGAF_AC
(
  IDE_CPT  VARCHAR2(15 BYTE),
  BE_D     NUMBER,
  BE_C     NUMBER,
  OA_D     NUMBER,
  OA_C     NUMBER,
  SA_D     NUMBER,
  SA_C     NUMBER,
  OFAI_D   NUMBER,
  OFAI_C   NUMBER,
  BS_D     NUMBER,
  BS_C     NUMBER,
  GRAS     CHAR(1 BYTE)
)
TABLESPACE ASTER_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT DELETE, INSERT, SELECT, UPDATE ON CGST.ETAT_CGAF_CGAF_AC TO PUBLIC;

--------------------- -----------------------------

DROP TABLE CGST.SERVICE_PAIERIE CASCADE CONSTRAINTS;

CREATE TABLE CGST.SERVICE_PAIERIE
(
  NOM_SERVICE     VARCHAR2(255 BYTE),
  IDE_CPT_DEBIT   VARCHAR2(25 BYTE),
  IDE_CPT_CREDIT  VARCHAR2(25 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


GRANT SELECT ON CGST.SERVICE_PAIERIE TO PUBLIC;


--------------------- -----------------------------



--------------------- -----------------------------


