SET DEFINE OFF;
Insert into FM_DEPECHE
   (IDE_ENV, IDE_SITE_EMET, IDE_SITE_DEST, IDE_DEPECHE, DAT_CRE, 
    DAT_EMIS, DAT_RECEP, COD_SUPPORT, COD_STATUT, FLG_EMIS_RECU, 
    NBR_MESS, IDE_TRT, FLG_MESS_APPLI, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL)
 Values
   ('X', 'CITFI', 'CITFI', 24871, TO_DATE('01/05/2023 08:05:48', 'DD/MM/YYYY HH24:MI:SS'), 
    TO_DATE('01/05/2023 08:05:47', 'DD/MM/YYYY HH24:MI:SS'), NULL, NULL, 'EN', 'E', 
    1, NULL, 'N', 'MES', TO_DATE('01/05/2023 08:05:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'MES', 'UNKNOWN');
COMMIT;
