SET DEFINE OFF;
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    1, 'C2020', 'T2012', 'TPI ABIDJAN', '44809', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 4350000, NULL, NULL, 
    NULL, 'REGLEMENT DIVERS VACATAIRES', NULL, NULL, '1', 
    'A', 'D 44809', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 4350000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    2, 'C2020', NULL, NULL, '531221', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 4350000, NULL, NULL, 
    NULL, 'REGLEMENT DIVERS VACATAIRES', NULL, NULL, '1', 
    'A', 'C 531221', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 4350000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    3, 'C2020', 'T2012', 'TPI ABIDJAN', '44809', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 600000, NULL, NULL, 
    NULL, 'VIREMENT KPITIME LEON', NULL, NULL, '1', 
    'A', 'D 44809', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 600000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    4, 'C2020', 'T2012', 'TPI ABIDJAN', '44809', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 990000, NULL, NULL, 
    NULL, 'VIREMENT CAC', NULL, NULL, '1', 
    'A', 'D 44809', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 990000, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    5, 'C2020', 'T2012', 'TPI ABIDJAN', '44809', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'D', 132710640, NULL, NULL, 
    NULL, 'VIREMENT TPI-CAA-TCA', NULL, NULL, '1', 
    'A', 'D 44809', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 132710640, NULL, NULL, 
    NULL);
Insert into FC_LIGNE
   (IDE_POSTE, IDE_GEST, IDE_JAL, FLG_CPTAB, IDE_ECR, 
    IDE_LIG, VAR_CPTA, VAR_TIERS, IDE_TIERS, IDE_CPT, 
    IDE_REF_PIECE, COD_REF_PIECE, VAR_BUD, IDE_LIG_EXEC, IDE_OPE, 
    IDE_ORDO, COD_SENS, MT, SPEC1, SPEC2, 
    SPEC3, OBSERV, DAT_CENTRA, DAT_TRANSF, IDE_SCHEMA, 
    COD_TYP_SCHEMA, IDE_MODELE_LIG, DAT_ECR, DAT_REF, COD_TYP_BUD, 
    COD_BUD, COD_BE, DAT_CRE, UTI_CRE, DAT_MAJ, 
    UTI_MAJ, TERMINAL, FLG_ANNUL_DCST, IDE_PLAN_AUX, IDE_CPT_AUX, 
    IDE_DEVISE, VAL_TAUX, MT_DEV, NUM_QUITTANCE, NOM_BQ, 
    CPT_BQ)
 Values
   ('862', '2023', 'T10BIS', 'O', 2, 
    6, 'C2020', NULL, NULL, '515112', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, 'C', 134300640, NULL, NULL, 
    NULL, 'VIREMENT DIVERS TRIBUNAUX', NULL, NULL, '1', 
    'A', 'C 515112', TO_DATE('10/01/2023', 'DD/MM/YYYY'), TO_DATE('10/01/2023', 'DD/MM/YYYY'), NULL, 
    NULL, NULL, TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 'A343712', TO_DATE('21/02/2023 12:15:55', 'DD/MM/YYYY HH24:MI:SS'), 
    'A343712', 'RDSASTER', 'N', NULL, NULL, 
    NULL, NULL, 134300640, NULL, NULL, 
    NULL);
COMMIT;
