-----------  TRANSFERT NUMERAIRE RECU POUR UN POSTE  ---------------

SELECT AGCODE, POSTE, AGLIB, LIBELLE, GESTION, MONTANT, JOURNEE, SCHEMA, JOURNAL, STATUT, COMPTE, SENS, DAT_TRANSF, DESTINATAIRE, GROUPE  FROM T_TRANSFERT_BIS_N a, T_AGENCE_ORAS b
WHERE GESTION='2022'
AND DESTINATAIRE='242C'
and a.EMETTEUR=b.AGCODE
ORDER BY JOURNEE, MONTANT, SENS
;

----------- TRANSFERT BANCAIRE RECU POUR UN POSTE ---------------

SELECT AGCODE, POSTE, AGLIB, LIBELLE, GESTION, MONTANT, JOURNEE, SCHEMA, JOURNAL, STATUT, COMPTE, SENS, DAT_TRANSF, DESTINATAIRE, GROUPE  FROM T_TRANSFERT_BIS_BANQ_N a, T_AGENCE_ORAS b
WHERE GESTION='2022'
--AND DESTINATAIRE='242C'
and a.EMETTEUR=b.AGCODE
ORDER BY JOURNEE, MONTANT, SENS
;

----------- TRANSFERT ORDRE 1 RECU POUR UN POSTE ---------------

SELECT AGCODE, POSTE, AGLIB, LIBELLE, GESTION, MONTANT, JOURNEE, SCHEMA, JOURNAL, STATUT, COMPTE, SENS, DAT_TRANSF, DESTINATAIRE, GROUPE  FROM T_TRANSFERT_BIS_ORDRE_OP1_AG_N a, T_AGENCE_ORAS b
WHERE GESTION='2022'
AND DESTINATAIRE='242C'
and a.EMETTEUR=b.AGCODE
ORDER BY JOURNEE, MONTANT, SENS
;

----------- TRANSFERT VIREMENT INTERNE (ORDRE 2)RECU POUR UN POSTE ---------------

SELECT AGCODE, POSTE, AGLIB, LIBELLE, GESTION, MONTANT, JOURNEE, SCHEMA, JOURNAL, STATUT, COMPTE, SENS, DAT_TRANSF, DESTINATAIRE, GROUPE  FROM T_TRANSFERT_BIS_ORDRE_OP2_AG_N a, T_AGENCE_ORAS b
WHERE GESTION='2022'
AND DESTINATAIRE='242C'
and a.EMETTEUR=b.AGCODE
ORDER BY JOURNEE, MONTANT, SENS
;

----------- T70P RECU POUR UN POSTE --------------

SELECT * FROM T_TRANSFERT_BIS_N
WHERE GESTION='2022'
AND EMETTEUR IN
(
SELECT AGCODE FROM T_AGENCE_ORAS
WHERE POSTEB='201'
AND DESTINATAIRE IS NULL
)
ORDER BY JOURNEE, MONTANT, SENS
;

------------

SELECT * FROM T_TRANSFERT_BIS_ORDRE_OP2_AG_N
WHERE GESTION='2022'
AND EMETTEUR IN
(
SELECT AGCODE FROM T_AGENCE_ORAS
WHERE POSTEB='242'
AND DESTINATAIRE IS NULL
)
ORDER BY JOURNEE, MONTANT, SENS
;